### ISSUE TITLE
SP800-53 Rev 5.2 improvements / EPIC

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/oscal-content#135]
# User Story:

In coordination with the NIST SP 800-53 Rev 5 update 2 release, we can stabilize all the corrections and enhancements it includes along with those accruing in this repository (work in progress), and update the OSCAL as appropriate.

This is a tracking issue for (check when addressed or ready):

- [ ] #101
- [ ] #112
- [ ] #123

## Goals:

- Track proposed changes and enhancements in detail
- Coordinate with FISMA team
- Make a timely release including all agreed changes

## Dependencies:

See above.

## Acceptance Criteria

- [ ] All readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] Issues are produced for follow-on questions
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by aj-stein-nist** [comment]
As an epic predating usnistgov/OSCAL#1688 board reorganization, I will want to label this as needs refinement for now until it can be broken down, rescoped, and or closed.
