### ISSUE TITLE
Define a version tracking policy in metadata for OSCAL SP800-53 catalog and profiles

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/oscal-content#47]
# User Story:

OSCAL metadata includes provision for formal version tracking in the document instance, but we have not used it so far for releases of SP800-53 data in OSCAL.

As processes become more regular and formal we should consider whether we should be using this feature, either for its utility, as a demonstration, or both.

## Goals:

Define a usage profile for change tracking of SP800-53 data (catalog and profiles) appropriate to its release/change management cycle.

Implement this usage in releases going forward, perhaps by integrating it into the production pipeline for these data sets.

## Dependencies:

None at present. But the design should reflect the needs of all stakeholders, including needs for both transparency, and low overhead.

## Acceptance Criteria

- [ ] All readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.
