### ISSUE TITLE
[EPIC] Revisit NIST SP 800-53A Modeling

### ISSUE THREAD

**Issue by brian-ruf** [usnistgov/oscal-content#67]
# User Story:

As an OSCAL modeler and content author, I need the OSCAL syntax to support various ways in which I may work with content from NIST SP 800-53A, and incorporate it into assessment activities. 

## Goals:

For 800-53A content:
- Ensure content is granular enough, and addressable (via IDs) at an appropriate level of granularity.
- Ensure existing and added ID assignments are logical and predictable to the degree practical.
- Provide the ability to map specific assessment activities (EXAMINE, INTERVIEW, TEST) to individual assessment objectives, instead of just assigned to the control as a whole.

## Dependencies:

None; however, this impacts the SAP and SAR Modeling (Issues usnistgov/OSCAL#589, usnistgov/OSCAL#617, and usnistgov/OSCAL#621).

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

- [ ] If necessary, catalog and profile syntax has been updated.
- [ ] All 800-53A assigned IDs are logical and predictable
- [ ] 800-53A content is modeled at the appropriate level of detail, with addressability (IDs) at an appropriate level of detail.

**Comment by david-waltermire-nist** [comment]
Some of this work has been addressed already, while some of this work, if desired, might require large-scale changes to the SP 800-53 content, which would be best done on a major version change. More discussion is needed to sort out the specific actions to take.
